---
- name: Add key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: EA312927
    state: present
    tags: install

- name: Add apt repository mongodb
  apt_repository:
    repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    filename: mongodb-org-3.2.list
    state: present
    tags: install

- name: Update repositories cache
  apt:
    update_cache: yes
    tags: install

- name: Install python-apt
  apt:
    name: python-apt
    state: present
    tags: install

- name: Install mongodb
  apt:
    name: mongodb-org
    state: present
    tags: install

- name: start puma
  systemd:
    name: mongodb
    state: started
    tags: install

- name: enable puma
  systemd:
    name: mongodb
    enabled: yes
    tags: install
