- name: Configure App
  hosts: app
  become: true
  roles:
    - app
    - role: jdauphant.nginx
      nginx_sites:
        custom_bar:
          template: custom_bar.conf.j2
          server_name: custom_bar.example.com