---
- name: Deploy application
  become: true
  hosts: app
  tasks:
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: "/home/{{ deploy_user }}/reddit"
        version: monolith # <-- Указываем нужную ветку
      notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        # В какой директории выполнить команду bundler
        chdir: "/home/{{ deploy_user }}/reddit"

  handlers: # <-- Добавим блок handlers и задачу
  - name: reload puma
    service: name=puma state=restarted
