---
- name: Configure MongoDB
  hosts: reddit-db
  become: true
  #tags: db-tag
  vars:
    mongo_bind_ip: 0.0.0.0
  tasks:
    - name: Change mongo config file
      template:
        dest: /etc/mongod.conf
        src: templates/mongod.conf.j2
        mode: 0644
      notify: restart mongod     

  handlers: # <-- Добавим блок handlers и задачу
  - name: restart mongod
    service: name=mongod state=restarted
